'use strict';

const crypto=require('crypto'); const net=require('net'); const PlatformApiKey=require('../models/PlatformApiKey'); const scopeRegistry=require('../config/developerScopes');
function pepper(){const value=process.env.PLATFORM_API_KEY_HASH_KEY||process.env.JWT_SECRET;if(!value)throw new Error('PLATFORM_API_KEY_HASH_KEY or JWT_SECRET is required');return value;}
function hashKey(value){return crypto.createHmac('sha256',pepper()).update(String(value)).digest('hex');}
function issueKey(environment='live'){const prefix=crypto.randomBytes(6).toString('hex');const secret=crypto.randomBytes(32).toString('base64url');return{prefix,plainText:`sk_${environment}_${prefix}_${secret}`};}
function validateScopes(scopes){const values=Array.from(new Set((scopes||[]).map(value=>String(value).trim().toLowerCase())));const invalid=values.filter(value=>!scopeRegistry.keys.includes(value));if(invalid.length)throw Object.assign(new Error(`Unknown API scopes: ${invalid.join(', ')}`),{statusCode:400});return values;}
async function createKey(input,actorId){const environment=input.environment==='sandbox'?'sandbox':'live';const scopes=validateScopes(input.scopes);if(environment==='sandbox'&&scopes.some(scope=>scope!=='platform.health.read'))throw Object.assign(new Error('Sandbox keys may only use platform.health.read and cannot access production data'),{statusCode:400});const ipAllowlist=Array.from(new Set((input.ipAllowlist||[]).map(String).map(v=>v.trim()).filter(Boolean))).slice(0,50);if(ipAllowlist.some(value=>!net.isIP(value)))throw Object.assign(new Error('IP allowlist accepts exact IPv4 or IPv6 addresses only'),{statusCode:400});const expiresAt=input.expiresAt?new Date(input.expiresAt):null;if(expiresAt&&(Number.isNaN(expiresAt.getTime())||expiresAt<=new Date()))throw Object.assign(new Error('API key expiration must be a valid future date'),{statusCode:400});const issued=issueKey(environment);const document=await PlatformApiKey.create({name:String(input.name||'').trim(),prefix:issued.prefix,secretHash:hashKey(issued.plainText),environment,scopes,ipAllowlist,rateLimitPerMinute:Number(input.rateLimitPerMinute)||60,expiresAt,createdBy:actorId});return{document,plainText:issued.plainText};}
async function authenticate(value){const match=/^sk_(live|sandbox)_([a-f0-9]{12})_[A-Za-z0-9_-]{40,60}$/.exec(String(value||''));if(!match)return null;const document=await PlatformApiKey.findOne({prefix:match[2]}).select('+secretHash');if(!document)return null;const actual=Buffer.from(document.secretHash,'hex');const expected=Buffer.from(hashKey(value),'hex');if(actual.length!==expected.length||!crypto.timingSafeEqual(actual,expected))return null;return document;}
function publicKey(item){return{_id:item._id,name:item.name,prefix:`sk_${item.environment}_${item.prefix}`,environment:item.environment,scopes:item.scopes,ipAllowlist:item.ipAllowlist,rateLimitPerMinute:item.rateLimitPerMinute,expiresAt:item.expiresAt,lastUsedAt:item.lastUsedAt,lastUsedIp:item.lastUsedIp,revokedAt:item.revokedAt,createdAt:item.createdAt};}
module.exports={hashKey,issueKey,validateScopes,createKey,authenticate,publicKey};
