'use strict';
const express = require('express');
const crypto = require('crypto');
const router = express.Router();
const { adminAuth } = require('../middleware/auth');
const CourierIntegration = require('../models/CourierIntegration');
const CourierSubmission = require('../models/CourierSubmission');
const Order = require('../models/Order');
const registry = require('../services/couriers/courierRegistry');
const { encryptSecret, decryptSecret } = require('../utils/secretCrypto');

function tid(req, res) { const id = req.user?.tenantId || req.tenantId; if (!id) { res.status(400).json({ message: 'Tenant context is required' }); return null; } return id; }
const selectSecrets = '+encryptedCredentials.ciphertext +encryptedCredentials.iv +encryptedCredentials.tag +encryptedCredentials.version';
function masked(row, definition) { if (!row) return { provider: definition.provider, displayName: definition.displayName, enabled: false, connectionStatus: 'not_tested', defaultPackageWeight: 1, fields: {} }; return { provider: row.provider, displayName: row.displayName || definition.displayName, enabled: row.enabled, environment: row.environment, defaultPackageWeight: row.defaultPackageWeight || 1, connectionStatus: row.connectionStatus, lastTestedAt: row.lastTestedAt, publicConfiguration: row.publicConfiguration || {}, capabilities: row.capabilities || definition.capabilities, hasCredentials: Boolean(row.encryptedCredentials?.ciphertext), fields: Object.fromEntries((definition.fields || []).map(f => [f.key, f.secret && row.encryptedCredentials?.ciphertext ? 'Saved — leave blank to preserve' : row.publicConfiguration?.[f.key] || ''])) }; }
function credentials(row) { return row?.encryptedCredentials?.ciphertext ? JSON.parse(decryptSecret(row.encryptedCredentials)) : {}; }

router.use(adminAuth);
router.get('/providers', (req, res) => res.json(registry.definitions()));
router.get('/', async (req, res) => { const id = tid(req, res); if (!id) return; const rows = await CourierIntegration.find({ tenantId: id, provider: { $ne: 'curfox' } }).lean(); res.json(rows.map(r => masked(r, registry.definition(r.provider)))); });
router.get('/:provider', async (req, res) => { const id = tid(req, res); if (!id) return; const def = registry.definition(req.params.provider); if (!def) return res.status(404).json({ message: 'Unsupported courier provider' }); const row = await CourierIntegration.findOne({ tenantId: id, provider: def.provider }).select(selectSecrets).lean(); res.json(masked(row, def)); });
router.post('/test', async (req, res) => { const id = tid(req, res); if (!id) return; const def = registry.definition(req.body.provider); if (!def) return res.status(400).json({ message: 'Unsupported courier provider' }); const row = await CourierIntegration.findOne({ tenantId: id, provider: def.provider }).select(selectSecrets); const supplied = req.body.credentials || {}; const saved = credentials(row); const merged = { ...saved, ...Object.fromEntries((def.fields || []).map(f => [f.key, supplied[f.key] || saved[f.key] || ''])) }; for (const f of def.fields || []) if (f.required && !merged[f.key]) return res.status(400).json({ message: `${f.label} is required` }); try { await registry.create(def.provider, req.body).testConnection(merged); await CourierIntegration.updateOne({ tenantId: id, provider: def.provider }, { $set: { connectionStatus: 'connected', lastTestedAt: new Date() } }); res.json({ success: true, connectionStatus: 'connected' }); } catch (err) { await CourierIntegration.updateOne({ tenantId: id, provider: def.provider }, { $set: { connectionStatus: 'failed', lastTestedAt: new Date() } }); res.status(err.response?.status || 502).json({ message: err.message }); } });
router.put('/:provider', async (req, res) => { const id = tid(req, res); if (!id) return; const def = registry.definition(req.params.provider); if (!def) return res.status(400).json({ message: 'Unsupported courier provider' }); const row = await CourierIntegration.findOne({ tenantId: id, provider: def.provider }).select(selectSecrets); const old = credentials(row); const incoming = req.body.credentials || {}; const merged = { ...old, ...Object.fromEntries((def.fields || []).map(f => [f.key, incoming[f.key] || old[f.key] || ''])) }; for (const f of def.fields || []) if (f.required && !merged[f.key]) return res.status(400).json({ message: `${f.label} is required` }); const publicConfiguration = { ...(req.body.publicConfiguration || {}) }; for (const f of def.fields || []) if (!f.secret && incoming[f.key] != null) publicConfiguration[f.key] = incoming[f.key]; const update = { provider: def.provider, displayName: def.displayName, environment: req.body.environment === 'sandbox' ? 'sandbox' : 'production', enabled: Boolean(req.body.enabled), defaultPackageWeight: Number(req.body.defaultPackageWeight) > 0 ? Number(req.body.defaultPackageWeight) : 1, publicConfiguration, capabilities: def.capabilities, updatedBy: req.user.email }; if (Object.keys(incoming).some(k => incoming[k])) update.encryptedCredentials = encryptSecret(JSON.stringify(merged)); const saved = await CourierIntegration.findOneAndUpdate({ tenantId: id, provider: def.provider }, { $set: update }, { upsert: true, new: true, runValidators: true }).select(selectSecrets); res.json(masked(saved, def)); });
router.patch('/:provider/status', async (req, res) => { const id = tid(req, res); if (!id) return; const row = await CourierIntegration.findOneAndUpdate({ tenantId: id, provider: req.params.provider }, { $set: { enabled: Boolean(req.body.enabled) } }, { new: true }); if (!row) return res.status(404).json({ message: 'Courier integration not found' }); res.json({ provider: row.provider, enabled: row.enabled }); });
router.delete('/:provider', async (req, res) => { const id = tid(req, res); if (!id) return; await CourierIntegration.deleteOne({ tenantId: id, provider: req.params.provider }); res.json({ success: true }); });
router.post('/:provider/orders/:orderId/submit', async (req, res) => { const id = tid(req, res); if (!id) return; const def = registry.definition(req.params.provider); if (!def) return res.status(400).json({ message: 'Unsupported courier provider' }); const order = await Order.findOne({ _id: req.params.orderId, tenantId: id }); if (!order) return res.status(404).json({ message: 'Order not found' }); const config = await CourierIntegration.findOne({ tenantId: id, provider: def.provider }).select(selectSecrets); if (!config?.enabled) return res.status(400).json({ message: 'Courier integration is disabled' }); const existing = await CourierSubmission.findOne({ tenantId: id, orderId: order._id, provider: def.provider }); if (existing && ['submitting','submitted','reconciliation_required'].includes(existing.state)) return res.status(409).json({ message: 'This order has already been submitted or is currently submitting', submissionState: existing.state }); const attemptId = crypto.randomUUID(); const submission = existing || await CourierSubmission.create({ tenantId: id, orderId: order._id, provider: def.provider, attemptId, state: 'submitting' }); submission.state = 'submitting'; submission.attemptId = attemptId; await submission.save(); try { const result = await registry.create(def.provider, config).submitOrder(order, credentials(config)); await CourierSubmission.updateOne({ _id: submission._id }, { $set: { state: 'submitted', externalId: result.externalId, responseReceivedAt: new Date() } }); const saved = await Order.findOneAndUpdate({ _id: order._id, tenantId: id }, { $set: { 'courier.provider': def.provider, 'courier.externalId': result.externalId, 'courier.waybill': result.waybill, 'courier.submissionState': 'submitted', 'courier.submittedAt': new Date(), trackingNumber: result.waybill, deliveryPartner: config.displayName || def.displayName } }, { new: true }); res.json(saved); } catch (err) { await CourierSubmission.updateOne({ _id: submission._id }, { $set: { state: 'failed', error: err.message } }); await Order.updateOne({ _id: order._id, tenantId: id }, { $set: { 'courier.provider': def.provider, 'courier.submissionState': 'failed', 'courier.submissionError': err.message } }); res.status(502).json({ message: err.message }); } });
router.get('/:provider/orders/:orderId/tracking', async (req, res) => { const id = tid(req, res); if (!id) return; const def = registry.definition(req.params.provider); const order = await Order.findOne({ _id: req.params.orderId, tenantId: id }); const config = await CourierIntegration.findOne({ tenantId: id, provider: req.params.provider }).select(selectSecrets); if (!def || !order || !config) return res.status(404).json({ message: 'Courier order or integration not found' }); try { const result = await registry.create(def.provider, config).getTracking(order, credentials(config)); const next = registry.create(def.provider, config).normalizeStatus(result.externalStatus, order.orderStatus); const update = { 'courier.trackingEvents': result.events, 'courier.externalStatus': result.externalStatus, 'courier.lastSynchronizedAt': new Date() }; if (next !== order.orderStatus) update.orderStatus = next; const saved = await Order.findOneAndUpdate({ _id: order._id, tenantId: id }, { $set: update }, { new: true }); res.json(saved); } catch (err) { res.status(502).json({ message: err.message }); } });
module.exports = router;
