'use strict';
const express=require('express'); const Tenant=require('../models/Tenant'); const DeploymentRecord=require('../models/DeploymentRecord'); const {platformApiAuth,requireApiScope}=require('../middleware/platformApiAuth'); const {platformAudit}=require('../middleware/platformAudit'); const analytics=require('../services/platformAnalyticsService'); const {recordDeployment}=require('../services/deploymentService');
const router=express.Router(); router.use(platformApiAuth,platformAudit);
function publicDeployment(item){const value=item?.toObject?item.toObject():item;return Object.fromEntries(['id','provider','externalId','environment','service','status','version','commitSha','branch','deploymentUrl','startedAt','completedAt','durationMs','source','createdAt','updatedAt'].map(key=>[key,key==='id'?String(value?._id||''):value?.[key]]));}
router.get('/health',requireApiScope('platform.health.read'),async(req,res)=>res.json({status:'ok',environment:req.platformApiKey.environment,time:new Date().toISOString(),apiVersion:'v1'}));
router.get('/tenants',requireApiScope('tenants.read'),async(req,res,next)=>{try{const limit=Math.min(Math.max(Number.parseInt(req.query.limit,10)||50,1),100);const after=String(req.query.after||'');const query={};if(after&&/^[a-f0-9]{24}$/i.test(after))query._id={$gt:after};const rows=await Tenant.find(query).select('storeName slug status plan subscription.status createdAt').populate('plan','name slug').sort({_id:1}).limit(limit+1).lean();const hasMore=rows.length>limit;const data=rows.slice(0,limit);res.set('Cache-Control','private, no-store').json({data,nextCursor:hasMore?String(data.at(-1)._id):null,hasMore});}catch(error){next(error);}});
router.get('/analytics/overview',requireApiScope('analytics.read'),async(_req,res,next)=>{try{res.set('Cache-Control','private, no-store').json(await analytics.overview({}));}catch(error){next(error);}});
router.get('/deployments',requireApiScope('deployments.read'),async(req,res,next)=>{try{const limit=Math.min(Math.max(Number.parseInt(req.query.limit,10)||50,1),100);const rows=await DeploymentRecord.find().sort({createdAt:-1}).limit(limit).select('-history').lean();res.set('Cache-Control','private, no-store').json({data:rows.map(publicDeployment)});}catch(error){next(error);}});
router.post('/deployments/events',requireApiScope('deployments.write'),async(req,res,next)=>{try{const item=await recordDeployment(req.body,{source:'platform_api',apiKeyId:req.platformApiKey._id});req.audit.set({action:'developer.deployment.record',resource:'deployment-record',resourceId:String(item._id),metadata:{apiKeyId:String(req.platformApiKey._id),environment:req.platformApiKey.environment,provider:item.provider,status:item.status,externalId:item.externalId}});res.set('Cache-Control','private, no-store').status(202).json({deployment:publicDeployment(item)});}catch(error){if(error.statusCode)return res.status(error.statusCode).json({message:error.message});if(error.code===11000)return res.status(409).json({message:'A concurrent deployment event was recorded; retry with the same idempotent payload'});next(error);}});
module.exports=router;
module.exports.publicDeployment=publicDeployment;
