'use strict';
const express = require('express');
const router = express.Router();
const mongoose = require('mongoose');
const Order = require('../models/Order');
const Product = require('../models/Product');
const InventoryMovement = require('../models/InventoryMovement');
const { adminAuth } = require('../middleware/auth');

const range = req => { const end = req.query.to ? new Date(req.query.to) : new Date(); const start = req.query.from ? new Date(req.query.from) : new Date(new Date().setHours(0, 0, 0, 0)); if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime())) throw new Error('Invalid date range'); return { createdAt: { $gte: start, $lte: end } }; };
router.get('/dashboard', adminAuth, async (req, res) => { const tenantId = req.tenantId; const filter = { tenantId, orderChannel: 'pos', paymentStatus: 'paid', ...range(req) }; const [sales, held, lowStock] = await Promise.all([Order.find(filter).select('total payments').lean(), require('../models/HeldPosSale').countDocuments({ tenantId }), Product.countDocuments({ tenantId, isActive: true, stock: { $lte: Number(req.query.lowStock || 5) } })]); const revenue = sales.reduce((s, x) => s + Number(x.total || 0), 0); const paymentTotals = {}; sales.forEach(x => (x.payments || []).forEach(p => { paymentTotals[p.method] = (paymentTotals[p.method] || 0) + Number(p.amount || 0); })); res.json({ revenue, transactions: sales.length, averageTransaction: sales.length ? revenue / sales.length : 0, paymentTotals, heldSales: held, lowStock }); });
router.get('/reports/sales', adminAuth, async (req, res) => { const rows = await Order.find({ tenantId: req.tenantId, orderChannel: 'pos', ...range(req) }).select('orderNumber total subtotal tax paymentStatus orderStatus createdAt payments').sort({ createdAt: -1 }).lean(); const gross = rows.filter(x => x.paymentStatus === 'paid').reduce((s, x) => s + Number(x.total || 0), 0); res.json({ rows, summary: { grossSales: gross, transactions: rows.length, averageTransaction: rows.length ? gross / rows.length : 0 } }); });
router.get('/inventory-movements', adminAuth, async (req, res) => { const filter = { tenantId: req.tenantId, ...range(req) }; if (req.query.type) filter.movementType = String(req.query.type); const rows = await InventoryMovement.find(filter).populate('product', 'name sku').sort({ createdAt: -1 }).limit(Math.min(200, Number(req.query.limit) || 50)).lean(); res.json({ rows }); });
router.post('/inventory-adjustments', adminAuth, async (req, res) => { const quantity = Number(req.body.quantity); if (!req.tenantId || !mongoose.isValidObjectId(req.body.productId) || !Number.isInteger(quantity) || quantity === 0 || !String(req.body.reason || '').trim()) return res.status(400).json({ message: 'Product, integer quantity, and reason are required' }); const product = await Product.findOne({ _id: req.body.productId, tenantId: req.tenantId, isActive: true }); if (!product) return res.status(404).json({ message: 'Product not found' }); const variant = req.body.variantSku ? (product.variantCombinations || []).find(v => v.sku === req.body.variantSku) : null; if (req.body.variantSku && !variant) return res.status(404).json({ message: 'Variant not found' }); const before = variant ? Number(variant.stock || 0) : Number(product.stock || 0); const after = before + quantity; if (after < 0) return res.status(400).json({ message: 'Stock cannot become negative' }); const update = variant ? { $inc: { 'variantCombinations.$.stock': quantity } } : { $inc: { stock: quantity } }; await Product.updateOne({ _id: product._id, tenantId: req.tenantId, ...(variant ? { 'variantCombinations.sku': variant.sku } : {}) }, update); const movement = await InventoryMovement.create({ tenantId: req.tenantId, product: product._id, variantSku: variant?.sku, movementType: 'manual_adjustment', quantityChange: quantity, quantityBefore: before, quantityAfter: after, sourceType: 'manual', createdBy: req.user?._id, createdByName: `${req.user?.firstName || ''} ${req.user?.lastName || ''}`.trim(), reason: req.body.reason, note: req.body.note }); res.status(201).json({ success: true, movement }); });
router.get('/reports/sales.csv', adminAuth, async (req, res) => { const rows = await Order.find({ tenantId: req.tenantId, orderChannel: 'pos', ...range(req) }).select('orderNumber total paymentStatus createdAt').lean(); const esc = v => `"${String(v ?? '').replace(/"/g, '""')}"`; res.type('text/csv').send(['Order,Total,Payment status,Date', ...rows.map(x => [x.orderNumber, x.total, x.paymentStatus, x.createdAt].map(esc).join(','))].join('\n')); });
module.exports = router;
