import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import API from '../../utils/api';
import { useAuth } from '../../context/AuthContext';

const FEATURE_KEYS = [
  'products','orders','categories','customers','coupons','giftCards','banners','seasonal','deals','reviews','subscribers','returns','seo','layoutEditor','themeBuilder','animations','socialMedia','aiPostCreator','automation','backup','billing','analytics','customDomain','metaPixel','wishlist','newsletter','guestCheckout','reviewApproval'
];
const defaultFeatures = FEATURE_KEYS.reduce((a,k)=>({ ...a, [k]: ['products','orders','categories','customers','customDomain','guestCheckout','billing'].includes(k) }), {});
const emptyPlan = { name:'', description:'', price:0, monthlyPrice:0, yearlyPrice:0, currency:'LKR', billingCycle:'monthly', trialDays:14, graceDays:7, autoSuspend:true, autoRenew:false, active:true, limits:{ products:100, ordersPerMonth:500, admins:2, storageMb:500 }, features: defaultFeatures };
const emptyTenant = { storeName:'', slug:'', domain:'', plan:'', adminEmail:'', adminPassword:'Admin@123456', adminFirstName:'Store', adminLastName:'Admin', settings:{ currency:'LKR', country:'Sri Lanka', timezone:'Asia/Colombo', whatsapp:'', phone:'', storeEmail:'' }, theme:{ primaryColor:'#15803d', accentColor:'#84cc16', darkColor:'#0f172a', fontFamily:'Inter', template:'modern-pro' }, subscription:{ billingCycle:'monthly' } };
const TABS = ['overview','plans','tenants','billing','payments','invoices','coupons','domains'];

function money(v,c='LKR'){ return `${c} ${Number(v||0).toLocaleString()}`; }
function date(v){ return v ? new Date(v).toLocaleDateString() : '-'; }
function setDeep(obj, path, value){ const keys=path.split('.'); const next={...obj}; let cur=next; keys.forEach((k,i)=>{ if(i===keys.length-1) cur[k]=value; else { cur[k]={...(cur[k]||{})}; cur=cur[k]; } }); return next; }

export default function SuperAdminDashboard(){
  const { user, logout } = useAuth();
  const [activeTab,setActiveTab]=useState('overview');
  const [sidebarOpen,setSidebarOpen]=useState(false);
  const [stats,setStats]=useState({ tenants:0, activeTenants:0, plans:0, admins:0 });
  const [plans,setPlans]=useState([]);
  const [tenants,setTenants]=useState([]);
  const [billing,setBilling]=useState({ metrics:{}, tenants:[], invoices:[], payments:[], coupons:[] });
  const [planForm,setPlanForm]=useState(emptyPlan);
  const [tenantForm,setTenantForm]=useState(emptyTenant);
  const [couponForm,setCouponForm]=useState({ code:'', description:'', type:'percentage', value:0, active:true });
  const [selectedTenantId,setSelectedTenantId]=useState('');
  const [domainInput,setDomainInput]=useState('');
  const [loading,setLoading]=useState(false);
  const [toast,setToast]=useState(null);

  const selectedTenant = useMemo(()=>tenants.find(t=>t._id===selectedTenantId),[tenants,selectedTenantId]);
  const notify = useCallback((type,text)=>{ setToast({type,text}); setTimeout(()=>setToast(null),4000); },[]);

  const loadAll = useCallback(async()=>{
    setLoading(true);
    try{
      const [statsRes, plansRes, tenantsRes, billingRes] = await Promise.all([
        API.get('/superadmin/stats'), API.get('/superadmin/plans'), API.get('/superadmin/tenants'), API.get('/superadmin/billing/summary')
      ]);
      setStats(statsRes.data); setPlans(plansRes.data); setTenants(tenantsRes.data); setBilling(billingRes.data);
      if(!tenantForm.plan && plansRes.data[0]?._id) setTenantForm(prev=>({ ...prev, plan: plansRes.data[0]._id }));
    }catch(err){ notify('error', err.response?.data?.message || err.message || 'Failed to load superadmin data'); }
    finally{ setLoading(false); }
  },[notify, tenantForm.plan]);

  useEffect(()=>{ loadAll(); },[loadAll]);

  async function savePlan(e){ e.preventDefault(); try{ await API.post('/superadmin/plans', planForm); setPlanForm(emptyPlan); notify('success','Plan created'); await loadAll(); }catch(err){ notify('error', err.response?.data?.message || err.message || 'Could not create plan'); } }
  async function updatePlan(plan){ try{ await API.put(`/superadmin/plans/${plan._id}`, plan); notify('success','Plan updated'); await loadAll(); }catch(err){ notify('error', err.response?.data?.message || err.message || 'Could not update plan'); } }
  async function createTenant(e){ e.preventDefault(); try{ await API.post('/superadmin/tenants', tenantForm); setTenantForm({ ...emptyTenant, plan: plans[0]?._id || '' }); notify('success','Tenant created and subscription started'); await loadAll(); }catch(err){ notify('error', err.response?.data?.message || err.message || 'Could not create tenant'); } }
  async function updateTenantRecord(id, patch){ try{ await API.put(`/superadmin/tenants/${id}`, patch); notify('success','Tenant updated'); await loadAll(); }catch(err){ notify('error', err.response?.data?.message || err.message || 'Could not update tenant'); } }
  async function runMaintenance(){ try{ await API.post('/superadmin/billing/maintenance/run'); notify('success','Billing maintenance completed'); await loadAll(); }catch(err){ notify('error', err.response?.data?.message || err.message || 'Maintenance failed'); } }
  async function approvePayment(id){ try{ await API.post(`/superadmin/billing/payments/${id}/approve`); notify('success','Payment approved and tenant renewed'); await loadAll(); }catch(err){ notify('error', err.response?.data?.message || err.message || 'Could not approve payment'); } }
  async function rejectPayment(id){ const note=window.prompt('Reject reason?') || ''; try{ await API.post(`/superadmin/billing/payments/${id}/reject`, { note }); notify('success','Payment rejected'); await loadAll(); }catch(err){ notify('error', err.response?.data?.message || err.message || 'Could not reject payment'); } }
  async function changeTenantPlan(t, planId){ try{ await API.post(`/superadmin/billing/tenants/${t._id}/change-plan`, { planId, billingCycle:t.subscription?.billingCycle || 'monthly' }); notify('success','Plan changed'); await loadAll(); }catch(err){ notify('error', err.response?.data?.message || err.message || 'Could not change plan'); } }
  async function generateInvoice(id){ try{ await API.post(`/superadmin/billing/tenants/${id}/renew`); notify('success','Invoice generated'); await loadAll(); }catch(err){ notify('error', err.response?.data?.message || err.message || 'Could not generate invoice'); } }
  async function saveCoupon(e){ e.preventDefault(); try{ await API.post('/superadmin/billing/coupons', couponForm); setCouponForm({ code:'', description:'', type:'percentage', value:0, active:true }); notify('success','Subscription coupon created'); await loadAll(); }catch(err){ notify('error', err.response?.data?.message || err.message || 'Could not save coupon'); } }
  async function addDomain(e){ e.preventDefault(); if(!selectedTenantId || !domainInput) return; try{ await API.post(`/superadmin/tenants/${selectedTenantId}/domains`, { domain:domainInput, type:'alias', verified:false }); setDomainInput(''); notify('success','Domain mapped'); await loadAll(); }catch(err){ notify('error', err.response?.data?.message || err.message || 'Could not map domain'); } }

  const sidebar = <aside className={`${sidebarOpen?'translate-x-0':'-translate-x-full'} fixed lg:static z-40 inset-y-0 left-0 w-72 bg-slate-950 text-white flex flex-col transition-transform lg:translate-x-0`}>
    <div className="p-5 border-b border-white/10"><Link to="/" className="font-black text-xl">StoreKit</Link><p className="text-xs text-slate-400 mt-1">Super Admin SaaS Control</p></div>
    <div className="px-5 py-4 border-b border-white/10"><p className="text-xs text-slate-500">Signed in</p><p className="text-sm truncate">{user?.email}</p></div>
    <nav className="flex-1 p-3 space-y-1 overflow-y-auto">{TABS.map(tab=><button key={tab} onClick={()=>{setActiveTab(tab);setSidebarOpen(false);}} className={`w-full text-left px-4 py-2.5 rounded-xl text-sm font-bold capitalize ${activeTab===tab?'bg-indigo-600 text-white':'text-slate-300 hover:bg-white/10'}`}>{tab}</button>)}</nav>
    <div className="p-3 border-t border-white/10"><button onClick={logout} className="w-full px-4 py-2 rounded-xl text-sm font-bold bg-red-500/10 text-red-300">Logout</button></div>
  </aside>;

  return <div className="flex h-screen bg-slate-50 overflow-hidden">
    {sidebarOpen && <div className="fixed inset-0 bg-black/40 z-30 lg:hidden" onClick={()=>setSidebarOpen(false)}/>} {sidebar}
    <div className="flex-1 flex flex-col min-w-0">
      <header className="h-16 bg-white border-b flex items-center justify-between px-4 lg:px-6"><div className="flex items-center gap-3"><button className="lg:hidden" onClick={()=>setSidebarOpen(true)}>☰</button><h1 className="font-black text-xl capitalize">{activeTab}</h1></div><div className="flex gap-3 items-center">{loading&&<span className="text-xs text-slate-400">Refreshing…</span>}<button onClick={loadAll} className="h-9 px-4 rounded-xl bg-slate-900 text-white text-xs font-bold">Refresh</button></div></header>
      {toast && <div className={`mx-4 mt-4 p-3 rounded-xl border text-sm font-bold ${toast.type==='error'?'bg-red-50 text-red-700 border-red-200':'bg-emerald-50 text-emerald-700 border-emerald-200'}`}>{toast.text}</div>}
      <main className="flex-1 overflow-y-auto p-4 lg:p-6 space-y-6">
        {activeTab==='overview' && <><div className="grid grid-cols-2 lg:grid-cols-6 gap-4"><Metric label="Tenants" value={stats.tenants}/><Metric label="Active" value={billing.metrics?.active||stats.activeTenants}/><Metric label="Trials" value={billing.metrics?.trialing||0}/><Metric label="Past Due" value={billing.metrics?.pastDue||0}/><Metric label="MRR" value={money(billing.metrics?.mrr)}/><Metric label="ARR" value={money(billing.metrics?.arr)}/></div><Panel title="Action Center"><div className="grid md:grid-cols-3 gap-4"><Action title="Run subscription automation" text="Updates trials, grace periods, invoices and suspensions." button="Run now" onClick={runMaintenance}/><Action title="Pending payments" text={`${billing.metrics?.pendingPayments||0} payment(s) waiting for approval.`} button="Review" onClick={()=>setActiveTab('payments')}/><Action title="Unpaid invoices" text={`${billing.metrics?.unpaidInvoices||0} invoice(s) require payment.`} button="View invoices" onClick={()=>setActiveTab('invoices')}/></div></Panel><TenantSubscriptionTable tenants={billing.tenants||tenants} plans={plans} onChangePlan={changeTenantPlan} onGenerateInvoice={generateInvoice}/></>}
        {activeTab==='plans' && <PlansTab plans={plans} planForm={planForm} setPlanForm={setPlanForm} savePlan={savePlan} updatePlan={updatePlan}/>} 
        {activeTab==='tenants' && <TenantsTab tenantForm={tenantForm} setTenantForm={setTenantForm} plans={plans} createTenant={createTenant} tenants={tenants} updateTenantRecord={updateTenantRecord}/>} 
        {activeTab==='billing' && <><div className="grid grid-cols-2 lg:grid-cols-5 gap-4"><Metric label="MRR" value={money(billing.metrics?.mrr)}/><Metric label="ARR" value={money(billing.metrics?.arr)}/><Metric label="Trialing" value={billing.metrics?.trialing||0}/><Metric label="Grace" value={billing.metrics?.grace||0}/><Metric label="Suspended" value={billing.metrics?.suspended||0}/></div><TenantSubscriptionTable tenants={billing.tenants||[]} plans={plans} onChangePlan={changeTenantPlan} onGenerateInvoice={generateInvoice}/></>}
        {activeTab==='payments' && <PaymentsTable payments={billing.payments||[]} onApprove={approvePayment} onReject={rejectPayment}/>} 
        {activeTab==='invoices' && <InvoicesTable invoices={billing.invoices||[]}/>} 
        {activeTab==='coupons' && <CouponsTab couponForm={couponForm} setCouponForm={setCouponForm} saveCoupon={saveCoupon} coupons={billing.coupons||[]}/>} 
        {activeTab==='domains' && <Panel title="Domain Mapping"><form onSubmit={addDomain} className="grid md:grid-cols-3 gap-3"><select className="input" value={selectedTenantId} onChange={e=>setSelectedTenantId(e.target.value)}><option value="">Select tenant</option>{tenants.map(t=><option key={t._id} value={t._id}>{t.storeName}</option>)}</select><input className="input" placeholder="example.lk" value={domainInput} onChange={e=>setDomainInput(e.target.value)}/><button className="btn">Map Domain</button></form>{selectedTenant&&<div className="mt-5 space-y-2">{(selectedTenant.domains||[]).map(d=><div key={d.domain} className="p-3 bg-slate-50 rounded-xl text-sm flex justify-between"><span>{d.domain}</span><span>{d.active?'Active':'Disabled'}</span></div>)}</div>}</Panel>}
      </main>
    </div>
  </div>;
}

function Metric({label,value}){return <div className="bg-white rounded-2xl border p-5"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="text-2xl font-black text-slate-900 mt-2">{value}</p></div>}
function Panel({title,children}){return <div className="bg-white rounded-2xl border border-slate-200 p-6"><h2 className="font-black text-slate-900 mb-4">{title}</h2>{children}</div>}
function Action({title,text,button,onClick}){return <div className="p-4 rounded-2xl bg-slate-50 border"><h3 className="font-bold text-slate-900">{title}</h3><p className="text-sm text-slate-500 mt-1 min-h-[42px]">{text}</p><button onClick={onClick} className="mt-4 h-10 px-4 rounded-xl bg-indigo-600 text-white text-sm font-bold">{button}</button></div>}
function Field({label,value,onChange,type='text',required=false}){return <label className="grid gap-1.5 text-xs font-bold text-slate-600">{label}<input className="input" type={type} value={value ?? ''} onChange={e=>onChange(type==='number'?Number(e.target.value):e.target.value)} required={required}/></label>}
function Status({s}){const c={active:'bg-emerald-50 text-emerald-700',trialing:'bg-blue-50 text-blue-700',past_due:'bg-orange-50 text-orange-700',grace:'bg-amber-50 text-amber-700',suspended:'bg-red-50 text-red-700',pending:'bg-amber-50 text-amber-700',approved:'bg-emerald-50 text-emerald-700',paid:'bg-emerald-50 text-emerald-700',rejected:'bg-red-50 text-red-700',unpaid:'bg-orange-50 text-orange-700',pending_review:'bg-amber-50 text-amber-700'}[s]||'bg-slate-50 text-slate-700';return <span className={`px-2 py-1 rounded-full text-xs font-bold ${c}`}>{String(s||'unknown').replace('_',' ')}</span>}

function PlansTab({plans,planForm,setPlanForm,savePlan,updatePlan}){return <div className="space-y-6"><Panel title="Create Subscription Plan"><form onSubmit={savePlan} className="grid md:grid-cols-4 gap-4"><Field label="Name" value={planForm.name} onChange={v=>setPlanForm(p=>({...p,name:v}))} required/><Field label="Monthly Price" type="number" value={planForm.monthlyPrice} onChange={v=>setPlanForm(p=>({...p,monthlyPrice:v,price:v}))}/><Field label="Yearly Price" type="number" value={planForm.yearlyPrice} onChange={v=>setPlanForm(p=>({...p,yearlyPrice:v}))}/><Field label="Trial Days" type="number" value={planForm.trialDays} onChange={v=>setPlanForm(p=>({...p,trialDays:v}))}/><Field label="Grace Days" type="number" value={planForm.graceDays} onChange={v=>setPlanForm(p=>({...p,graceDays:v}))}/><Field label="Product Limit" type="number" value={planForm.limits.products} onChange={v=>setPlanForm(p=>setDeep(p,'limits.products',v))}/><Field label="Admins" type="number" value={planForm.limits.admins} onChange={v=>setPlanForm(p=>setDeep(p,'limits.admins',v))}/><Field label="Currency" value={planForm.currency} onChange={v=>setPlanForm(p=>({...p,currency:v}))}/><div className="md:col-span-4"><FeatureToggles features={planForm.features} onChange={features=>setPlanForm(p=>({...p,features}))}/></div><button className="btn md:col-span-4">Create Plan</button></form></Panel><Panel title="Existing Plans"><div className="grid md:grid-cols-2 gap-4">{plans.map(p=><PlanCard key={p._id} plan={p} onSave={updatePlan}/>)}</div></Panel></div>}
function PlanCard({plan,onSave}){const [draft,setDraft]=useState(plan); useEffect(()=>setDraft(plan),[plan]); return <div className="p-4 rounded-2xl border bg-white space-y-3"><Field label="Name" value={draft.name} onChange={v=>setDraft(p=>({...p,name:v}))}/><div className="grid grid-cols-2 gap-3"><Field label="Monthly" type="number" value={draft.monthlyPrice||draft.price} onChange={v=>setDraft(p=>({...p,monthlyPrice:v,price:v}))}/><Field label="Yearly" type="number" value={draft.yearlyPrice} onChange={v=>setDraft(p=>({...p,yearlyPrice:v}))}/><Field label="Trial" type="number" value={draft.trialDays} onChange={v=>setDraft(p=>({...p,trialDays:v}))}/><Field label="Grace" type="number" value={draft.graceDays} onChange={v=>setDraft(p=>({...p,graceDays:v}))}/></div><FeatureToggles features={draft.features||{}} onChange={features=>setDraft(p=>({...p,features}))}/><button onClick={()=>onSave(draft)} className="btn w-full">Save Plan</button></div>}
function FeatureToggles({features,onChange}){return <div className="grid grid-cols-2 md:grid-cols-4 gap-2">{FEATURE_KEYS.map(k=><label key={k} className="flex items-center gap-2 text-xs bg-slate-50 rounded-xl px-3 py-2"><input type="checkbox" checked={!!features?.[k]} onChange={()=>onChange({...features,[k]:!features?.[k]})}/>{k}</label>)}</div>}
function TenantsTab({tenantForm,setTenantForm,plans,createTenant,tenants,updateTenantRecord}){return <div className="space-y-6"><Panel title="Create Tenant with Automated Trial"><form onSubmit={createTenant} className="grid md:grid-cols-4 gap-4"><Field label="Store Name" value={tenantForm.storeName} onChange={v=>setTenantForm(p=>({...p,storeName:v}))} required/><Field label="Slug" value={tenantForm.slug} onChange={v=>setTenantForm(p=>({...p,slug:v}))} required/><Field label="Domain" value={tenantForm.domain} onChange={v=>setTenantForm(p=>({...p,domain:v}))}/><label className="grid gap-1.5 text-xs font-bold text-slate-600">Plan<select className="input" value={tenantForm.plan} onChange={e=>setTenantForm(p=>({...p,plan:e.target.value}))}>{plans.map(p=><option key={p._id} value={p._id}>{p.name}</option>)}</select></label><Field label="Admin Email" value={tenantForm.adminEmail} onChange={v=>setTenantForm(p=>({...p,adminEmail:v}))} required/><Field label="Admin Password" value={tenantForm.adminPassword} onChange={v=>setTenantForm(p=>({...p,adminPassword:v}))}/><button className="btn md:col-span-4">Create Store + Start Subscription</button></form></Panel><TenantSubscriptionTable tenants={tenants} plans={plans} onChangePlan={(t,planId)=>updateTenantRecord(t._id,{plan:planId})} onGenerateInvoice={()=>{}}/></div>}
function TenantSubscriptionTable({tenants,plans,onChangePlan,onGenerateInvoice}){return <Panel title="Tenant Subscriptions"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-slate-400 border-b"><th className="py-2">Store</th><th>Plan</th><th>Status</th><th>Next Billing</th><th>Grace</th><th>Actions</th></tr></thead><tbody>{tenants.map(t=><tr key={t._id} className="border-b"><td className="py-3 font-bold">{t.storeName}<div className="text-xs text-slate-400">{(t.domains||[])[0]?.domain}</div></td><td><select className="input !h-9" value={t.plan?._id||t.plan||''} onChange={e=>onChangePlan(t,e.target.value)}>{plans.map(p=><option key={p._id} value={p._id}>{p.name}</option>)}</select></td><td><Status s={t.subscription?.status||t.status}/></td><td>{date(t.subscription?.nextBillingAt)}</td><td>{date(t.subscription?.graceEndsAt)}</td><td><button onClick={()=>onGenerateInvoice(t._id)} className="px-3 py-1 rounded-lg bg-slate-900 text-white text-xs font-bold">Invoice</button></td></tr>)}</tbody></table></div></Panel>}
function PaymentsTable({payments,onApprove,onReject}){return <Panel title="Payment Approval Queue"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-slate-400 border-b"><th className="py-2">Store</th><th>Amount</th><th>Reference</th><th>Proof</th><th>Status</th><th>Actions</th></tr></thead><tbody>{payments.map(p=><tr key={p._id} className="border-b"><td className="py-3 font-bold">{p.tenantId?.storeName||'-'}</td><td>{money(p.amount,p.currency)}</td><td>{p.reference||'-'}</td><td>{p.proofUrl?<a className="text-indigo-600" href={p.proofUrl} target="_blank" rel="noreferrer">Open</a>:'-'}</td><td><Status s={p.status}/></td><td>{p.status==='pending'&&<div className="flex gap-2"><button onClick={()=>onApprove(p._id)} className="px-3 py-1 rounded-lg bg-emerald-600 text-white text-xs font-bold">Approve</button><button onClick={()=>onReject(p._id)} className="px-3 py-1 rounded-lg bg-red-600 text-white text-xs font-bold">Reject</button></div>}</td></tr>)}</tbody></table></div></Panel>}
function InvoicesTable({invoices}){return <Panel title="Invoices"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-slate-400 border-b"><th className="py-2">Invoice</th><th>Store</th><th>Due</th><th>Total</th><th>Status</th></tr></thead><tbody>{invoices.map(i=><tr key={i._id} className="border-b"><td className="py-3 font-bold">{i.invoiceNumber}</td><td>{i.tenantId?.storeName||'-'}</td><td>{date(i.dueDate)}</td><td>{money(i.total,i.currency)}</td><td><Status s={i.status}/></td></tr>)}</tbody></table></div></Panel>}
function CouponsTab({couponForm,setCouponForm,saveCoupon,coupons}){return <div className="space-y-6"><Panel title="Create Subscription Coupon"><form onSubmit={saveCoupon} className="grid md:grid-cols-5 gap-4"><Field label="Code" value={couponForm.code} onChange={v=>setCouponForm(p=>({...p,code:v}))} required/><label className="grid gap-1.5 text-xs font-bold text-slate-600">Type<select className="input" value={couponForm.type} onChange={e=>setCouponForm(p=>({...p,type:e.target.value}))}><option value="percentage">Percentage</option><option value="fixed">Fixed</option></select></label><Field label="Value" type="number" value={couponForm.value} onChange={v=>setCouponForm(p=>({...p,value:v}))}/><Field label="Description" value={couponForm.description} onChange={v=>setCouponForm(p=>({...p,description:v}))}/><button className="btn self-end">Create</button></form></Panel><Panel title="Coupons"><div className="grid md:grid-cols-3 gap-3">{coupons.map(c=><div key={c._id} className="p-4 rounded-2xl bg-slate-50"><p className="font-black">{c.code}</p><p className="text-sm text-slate-500">{c.type} {c.value}</p><Status s={c.active?'active':'disabled'}/></div>)}</div></Panel></div>}

