'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');
process.env.JWT_SECRET=process.env.JWT_SECRET||'platform-user-tests-strong-secret';
const User=require('../models/User');const PlatformAccountToken=require('../models/PlatformAccountToken');const accounts=require('../services/platformAccountService');
test('platform account tokens are one-time hashed expiring records',()=>{assert.equal(PlatformAccountToken.schema.path('tokenHash').options.select,false);assert.equal(PlatformAccountToken.schema.path('tokenHash').options.unique,true);assert.ok(PlatformAccountToken.schema.indexes().some(([keys,options])=>keys.expiresAt===1&&options.expireAfterSeconds));const token=accounts.issueToken();assert.equal(accounts.hashToken(token).length,64);assert.notEqual(accounts.hashToken(token),token);});
test('platform password policy requires mixed character classes',()=>{assert.equal(accounts.validatePassword('weak').valid,false);assert.equal(accounts.validatePassword('Strong@123').valid,true);});
test('new operators and MFA resets enforce enrollment before Control Center access',()=>{assert.ok(User.schema.path('mfaEnrollmentRequired'));const accountRoute=fs.readFileSync(path.join(__dirname,'../routes/platformAccount.js'),'utf8');const accessRoute=fs.readFileSync(path.join(__dirname,'../routes/superadmin/access.js'),'utf8');const superadmin=fs.readFileSync(path.join(__dirname,'../routes/superadmin.js'),'utf8');assert.match(accountRoute,/mfaEnrollmentRequired:true/);assert.match(accessRoute,/mfaEnrollmentRequired=true/);assert.match(superadmin,/MFA_ENROLLMENT_REQUIRED/);});
test('password reset preserves existing MFA while explicit reset revokes sessions',()=>{const accountRoute=fs.readFileSync(path.join(__dirname,'../routes/platformAccount.js'),'utf8');const accessRoute=fs.readFileSync(path.join(__dirname,'../routes/superadmin/access.js'),'utf8');assert.doesNotMatch(accountRoute,/MfaFactor\.delete/);assert.match(accessRoute,/MfaFactor\.deleteOne/);assert.match(accessRoute,/revokeAllUserSessions/);});
test('high-risk platform user lifecycle actions require recent MFA and audit events',()=>{const source=fs.readFileSync(path.join(__dirname,'../routes/superadmin/access.js'),'utf8');for(const action of ['users/invite','password-reset','mfa-reset','users/:id'])assert.ok(source.includes(action));assert.match(source,/users\.delete.*requireRecentStepUp/s);assert.match(source,/users\.suspend.*requireRecentStepUp/s);assert.match(source,/platform-user\.delete/);assert.match(source,/platform-user\.invite/);});
