'use strict';

const express = require('express');
const { requirePlatformPermission } = require('../../services/platformAuthorizationService');
const analytics = require('../../services/platformAnalyticsService');
const AcquisitionCost = require('../../models/AcquisitionCost');
const mongoose = require('mongoose');
const { requireRecentStepUp } = require('../../middleware/stepUp');
const { acquisitionSyncStatus, boundedDays, googleAdsSyncStatus, syncGoogleAdsSpend, syncMetaAdsSpend } = require('../../services/acquisitionSyncService');
const { runTrackedJob } = require('../../services/operationsService');

const router = express.Router();
function dates(query) { const from = query.from ? new Date(query.from) : undefined; const to = query.to ? new Date(query.to) : undefined; if ((from && Number.isNaN(from.getTime())) || (to && Number.isNaN(to.getTime())) || (from && to && from >= to)) throw Object.assign(new Error('Analytics date range is invalid'), { statusCode: 400 }); return { from, to }; }
router.get('/overview', requirePlatformPermission('analytics.view'), async (req,res,next)=>{try{res.json(await analytics.overview(dates(req.query)));}catch(error){if(error.statusCode)return res.status(error.statusCode).json({message:error.message});next(error);}});
router.get('/timeseries', requirePlatformPermission('analytics.view'), async (req,res,next)=>{try{res.json(await analytics.timeSeries({months:req.query.months}));}catch(error){next(error);}});
router.get('/retention', requirePlatformPermission('analytics.view'), async (req,res,next)=>{try{res.json(await analytics.retention({cohorts:req.query.cohorts}));}catch(error){next(error);}});
router.get('/feature-adoption', requirePlatformPermission('analytics.view'), async (req,res,next)=>{try{res.json(await analytics.featureAdoption({days:req.query.days}));}catch(error){next(error);}});
router.get('/commerce-funnel', requirePlatformPermission('analytics.view'), async (req,res,next)=>{try{res.json(await analytics.commerceFunnel(dates(req.query)));}catch(error){if(error.statusCode)return res.status(error.statusCode).json({message:error.message});next(error);}});
router.get('/click-heatmap', requirePlatformPermission('analytics.view'), async(req,res,next)=>{try{const pages=['','home','shop','category','brand','product','cart','checkout','account','orders','wishlist','returns','content','other'];const page=String(req.query.page||'');if(!pages.includes(page))return res.status(400).json({message:'Unsupported heatmap page'});const tenantId=req.query.tenantId?String(req.query.tenantId):null;if(tenantId&&!mongoose.isValidObjectId(tenantId))return res.status(400).json({message:'Invalid heatmap tenant identifier'});res.json(await analytics.clickHeatmap({days:req.query.days,page,tenantId}));}catch(error){next(error);}});
router.get('/acquisition-costs', requirePlatformPermission('analytics.view'), async (req,res,next)=>{try{const range=dates(req.query);const filter={};if(range.from||range.to)filter.incurredAt={...(range.from?{$gte:range.from}:{}),...(range.to?{$lte:range.to}:{})};const costs=await AcquisitionCost.find(filter).populate('createdBy','email').sort({incurredAt:-1}).limit(500).lean();res.json({costs});}catch(error){if(error.statusCode)return res.status(error.statusCode).json({message:error.message});next(error);}});
router.get('/acquisition-sync', requirePlatformPermission('analytics.view'), async(_req,res,next)=>{try{res.json(await acquisitionSyncStatus());}catch(error){next(error);}});
router.get('/acquisition-sync/google-ads', requirePlatformPermission('analytics.view'), async(_req,res,next)=>{try{res.json(await googleAdsSyncStatus());}catch(error){next(error);}});
router.post('/acquisition-sync/meta-ads', requirePlatformPermission('analytics.manage'), requireRecentStepUp(), async(req,res,next)=>{try{const days=boundedDays(req.body?.days);const result=await runTrackedJob('acquisition-meta-ads-sync',()=>syncMetaAdsSpend({actorId:req.user._id,days}),{provider:'meta-ads',trigger:'manual',days});req.audit.set({action:'analytics.acquisition-sync.meta-ads',resource:'acquisition-cost',metadata:{days,processed:result.processed,failed:result.failed,upserted:result.upserted,modified:result.modified,currency:result.currency}});res.json({result,status:await acquisitionSyncStatus()});}catch(error){if(error.statusCode)return res.status(error.statusCode).json({message:error.message});res.status(502).json({message:'Meta Ads synchronization failed. Review the redacted sync status and Operations job log.'});}});
router.post('/acquisition-sync/google-ads', requirePlatformPermission('analytics.manage'), requireRecentStepUp(), async(req,res,next)=>{try{const days=boundedDays(req.body?.days);const result=await runTrackedJob('acquisition-google-ads-sync',()=>syncGoogleAdsSpend({actorId:req.user._id,days}),{provider:'google-ads',trigger:'manual',days});req.audit.set({action:'analytics.acquisition-sync.google-ads',resource:'acquisition-cost',metadata:{days,processed:result.processed,failed:result.failed,upserted:result.upserted,modified:result.modified,currencies:result.currencies}});res.json({result,status:await googleAdsSyncStatus()});}catch(error){if(error.statusCode)return res.status(error.statusCode).json({message:error.message});res.status(502).json({message:'Google Ads synchronization failed. Review the redacted sync status and Operations job log.'});}});
function costPayload(body){const incurredAt=new Date(body?.incurredAt);const source=String(body?.source||'').trim().slice(0,80);const campaign=String(body?.campaign||'').trim().slice(0,160);const amount=Number(body?.amount);const currency=String(body?.currency||'').trim().toUpperCase();if(Number.isNaN(incurredAt.getTime())||incurredAt>new Date())throw Object.assign(new Error('A valid non-future incurred date is required'),{statusCode:400});if(!source)throw Object.assign(new Error('Acquisition source is required'),{statusCode:400});if(!Number.isFinite(amount)||amount<=0)throw Object.assign(new Error('Acquisition amount must be greater than zero'),{statusCode:400});if(!/^[A-Z]{3}$/.test(currency))throw Object.assign(new Error('Currency must be a three-letter ISO code'),{statusCode:400});return{incurredAt,source,campaign,amount:Math.round((amount+Number.EPSILON)*100)/100,currency,notes:String(body?.notes||'').trim().slice(0,1000),externalReference:String(body?.externalReference||'').trim().slice(0,200)||undefined};}
router.post('/acquisition-costs', requirePlatformPermission('analytics.manage'), requireRecentStepUp(), async(req,res,next)=>{try{const payload=costPayload(req.body);const cost=await AcquisitionCost.create({...payload,createdBy:req.user._id});req.audit.set({action:'analytics.acquisition-cost.create',resource:'acquisition-cost',resourceId:String(cost._id),changes:{newValue:payload}});res.status(201).json(cost);}catch(error){if(error.statusCode)return res.status(error.statusCode).json({message:error.message});if(error.code===11000)return res.status(409).json({message:'This external acquisition reference already exists'});next(error);}});
router.put('/acquisition-costs/:id', requirePlatformPermission('analytics.manage'), requireRecentStepUp(), async(req,res,next)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid acquisition cost identifier'});const existing=await AcquisitionCost.findById(req.params.id);if(!existing)return res.status(404).json({message:'Acquisition cost not found'});const payload=costPayload(req.body);const oldValue=existing.toObject();Object.assign(existing,payload);await existing.save();req.audit.set({action:'analytics.acquisition-cost.update',resource:'acquisition-cost',resourceId:String(existing._id),changes:{oldValue,newValue:payload}});res.json(existing);}catch(error){if(error.statusCode)return res.status(error.statusCode).json({message:error.message});if(error.code===11000)return res.status(409).json({message:'This external acquisition reference already exists'});next(error);}});
router.delete('/acquisition-costs/:id', requirePlatformPermission('analytics.manage'), requireRecentStepUp(), async(req,res,next)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid acquisition cost identifier'});const cost=await AcquisitionCost.findByIdAndDelete(req.params.id);if(!cost)return res.status(404).json({message:'Acquisition cost not found'});req.audit.set({action:'analytics.acquisition-cost.delete',resource:'acquisition-cost',resourceId:String(cost._id),changes:{oldValue:cost.toObject()}});res.json({message:'Acquisition cost deleted'});}catch(error){next(error);}});
function csvCell(value){const text=typeof value==='object'?JSON.stringify(value):String(value??'');const safe=/^[=+\-@]/.test(text)?`'${text}`:text;return `"${safe.replaceAll('"','""')}"`;}
router.get('/export.csv', requirePlatformPermission('analytics.export'), async (req,res,next)=>{try{const data=await analytics.timeSeries({months:req.query.months});const currencies=Array.from(new Set(data.rows.flatMap(row=>[...Object.keys(row.netCollections),...Object.keys(row.storefrontGmv)]))).sort();const headers=['month','tenant_signups','tenant_cancellations','storefront_orders',...currencies.flatMap(currency=>[`net_collections_${currency}`,`storefront_gmv_${currency}`])];const lines=[headers.map(csvCell).join(','),...data.rows.map(row=>[row.month,row.signups,row.cancellations,row.storefrontOrders,...currencies.flatMap(currency=>[row.netCollections[currency]||0,row.storefrontGmv[currency]||0])].map(csvCell).join(','))];res.set({'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="storekit-platform-analytics.csv"','Cache-Control':'private, no-store'}).send(`\uFEFF${lines.join('\n')}`);}catch(error){next(error);}});
module.exports=router;
