'use strict';

const express = require('express');
const SupportTicket = require('../../models/SupportTicket');
const SupportMessage = require('../../models/SupportMessage');
const KnowledgeArticle = require('../../models/KnowledgeArticle');
const User = require('../../models/User');
const { requirePlatformPermission } = require('../../services/platformAuthorizationService');
const { addMessage, deadlines } = require('../../services/supportService');
const supportRealtime = require('../../services/supportRealtimeService');

const router = express.Router();
router.get('/stream', requirePlatformPermission('support.view'), (req, res) => supportRealtime.connect(req, res, { platform: true, userId: req.user._id }));
router.get('/overview', requirePlatformPermission('support.view'), async (_req, res, next) => { try { const now = new Date(); const [open, urgent, breached, unassigned] = await Promise.all([SupportTicket.countDocuments({ status: { $nin: ['resolved','closed'] } }), SupportTicket.countDocuments({ priority: 'urgent', status: { $nin: ['resolved','closed'] } }), SupportTicket.countDocuments({ status: { $nin: ['resolved','closed'] }, $or: [{ firstRespondedAt: null, firstResponseDueAt: { $lt: now } }, { resolutionDueAt: { $lt: now } }] }), SupportTicket.countDocuments({ assignee: null, status: { $nin: ['resolved','closed'] } })]); res.json({ open, urgent, breached, unassigned, realtime: supportRealtime.health() }); } catch (error) { next(error); } });
router.get('/agents', requirePlatformPermission('support.view'), async (_req, res, next) => { try { res.json(await User.find({ role: 'superadmin', isActive: true }).select('firstName lastName email').sort({ firstName: 1 }).lean()); } catch (error) { next(error); } });
router.get('/tickets', requirePlatformPermission('support.view'), async (req, res, next) => { try { const query = {}; if (req.query.status) query.status = req.query.status; if (req.query.priority) query.priority = req.query.priority; if (req.query.assignee === 'unassigned') query.assignee = null; const search = String(req.query.search || '').trim(); if (search) query.$or = [{ number: new RegExp(search.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i') }, { subject: new RegExp(search.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i') }]; res.json(await SupportTicket.find(query).populate('tenant', 'storeName slug').populate('requester assignee', 'firstName lastName email').sort({ lastMessageAt: -1 }).limit(300).lean()); } catch (error) { next(error); } });
router.get('/tickets/:id', requirePlatformPermission('support.view'), async (req, res, next) => { try { const ticket = await SupportTicket.findById(req.params.id).populate('tenant', 'storeName slug status').populate('requester assignee', 'firstName lastName email').lean(); if (!ticket) return res.status(404).json({ message: 'Ticket not found' }); const messages = await SupportMessage.find({ ticket: ticket._id }).populate('author', 'firstName lastName email role').sort({ createdAt: 1 }).lean(); res.json({ ticket, messages }); } catch (error) { next(error); } });
router.post('/tickets/:id/messages', requirePlatformPermission('support.reply'), async (req, res, next) => { try { const ticket = await SupportTicket.findById(req.params.id).populate('tenant', 'storeName').populate('requester', 'firstName lastName email'); if (!ticket) return res.status(404).json({ message: 'Ticket not found' }); if (!req.body?.body) return res.status(400).json({ message: 'Message is required' }); const kind = req.body.kind === 'internal_note' ? 'internal_note' : 'reply'; const message = await addMessage(ticket, { author: req.user._id, body: String(req.body.body), kind, platformAgent: true }); req.audit.set({ action: kind === 'internal_note' ? 'support.internal-note' : 'support.reply', resource: 'support-ticket', resourceId: req.params.id }); if (kind !== 'internal_note' && ticket.tenant) { try { const Notification = require('../../models/index').Notification; await Notification.create({ tenantId: ticket.tenant._id || ticket.tenant, type: 'support_reply', title: `Support Reply: ${ticket.subject}`, message: `${req.user.firstName} ${req.user.lastName} replied to ticket #${ticket.number}`, link: '/admin/support', data: { ticketId: String(ticket._id), ticketNumber: ticket.number, superAdminId: String(req.user._id) }, }); } catch (notifErr) { console.error('[SUPPORT_REPLY_NOTIFICATION_FAILED]', notifErr.message); } } res.status(201).json(message); } catch (error) { next(error); } });
router.put('/tickets/:id', requirePlatformPermission('support.manage'), async (req, res, next) => { try { const ticket = await SupportTicket.findById(req.params.id); if (!ticket) return res.status(404).json({ message: 'Ticket not found' }); const oldValue = ticket.toObject(); if (['low','normal','high','urgent'].includes(req.body.priority) && req.body.priority !== ticket.priority) { ticket.priority = req.body.priority; Object.assign(ticket, deadlines(ticket.priority, ticket.createdAt)); } if (['open','pending_customer','pending_internal','resolved','closed'].includes(req.body.status)) { ticket.status = req.body.status; if (req.body.status === 'resolved') ticket.resolvedAt = new Date(); } if (req.body.assignee !== undefined) ticket.assignee = req.body.assignee || null; if (req.body.tags) ticket.tags = Array.from(new Set(req.body.tags.map(value => String(value).trim().toLowerCase()).filter(Boolean))).slice(0, 20); await ticket.save(); req.audit.set({ action: 'support-ticket.update', resource: 'support-ticket', resourceId: req.params.id, changes: { oldValue, newValue: ticket.toObject() } }); res.json(ticket); } catch (error) { next(error); } });
router.post('/tickets/:id/escalate', requirePlatformPermission('support.manage'), async (req, res, next) => { try { const reason = String(req.body?.reason || '').trim(); if (!reason) return res.status(400).json({ message: 'Escalation reason is required' }); const ticket = await SupportTicket.findByIdAndUpdate(req.params.id, { $set: { escalatedAt: new Date(), escalationReason: reason, priority: 'urgent', status: 'pending_internal', ...deadlines('urgent') } }, { new: true }); if (!ticket) return res.status(404).json({ message: 'Ticket not found' }); await SupportMessage.create({ ticket: ticket._id, tenant: ticket.tenant, author: req.user._id, kind: 'system', body: `Escalated: ${reason}` }); req.audit.set({ action: 'support-ticket.escalate', resource: 'support-ticket', resourceId: req.params.id }); res.json(ticket); } catch (error) { next(error); } });

router.get('/knowledge', requirePlatformPermission('support.view'), async (_req, res, next) => { try { res.json(await KnowledgeArticle.find().sort({ updatedAt: -1 }).lean()); } catch (error) { next(error); } });
router.post('/knowledge', requirePlatformPermission('support.manage'), async (req, res, next) => { try { if (!req.body?.title || !req.body?.body) return res.status(400).json({ message: 'Title and body are required' }); const slug = String(req.body.slug || req.body.title).toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''); const item = await KnowledgeArticle.create({ slug, title: req.body.title, summary: req.body.summary, body: req.body.body, category: req.body.category, status: req.body.status || 'draft', publishedAt: req.body.status === 'published' ? new Date() : null, createdBy: req.user._id, updatedBy: req.user._id }); req.audit.set({ action: 'knowledge.create', resource: 'knowledge-article', resourceId: String(item._id) }); res.status(201).json(item); } catch (error) { if (error.code === 11000) return res.status(409).json({ message: 'Knowledge article slug already exists' }); next(error); } });
router.put('/knowledge/:id', requirePlatformPermission('support.manage'), async (req, res, next) => { try { const update = {}; for (const key of ['title','summary','body','category','status']) if (req.body[key] !== undefined) update[key] = req.body[key]; update.updatedBy = req.user._id; if (req.body.status === 'published') update.publishedAt = new Date(); const item = await KnowledgeArticle.findByIdAndUpdate(req.params.id, { $set: update }, { new: true, runValidators: true }); if (!item) return res.status(404).json({ message: 'Article not found' }); req.audit.set({ action: 'knowledge.update', resource: 'knowledge-article', resourceId: req.params.id }); res.json(item); } catch (error) { next(error); } });
module.exports = router;
